version: '3.8'

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "paper"
      VERSION: "latest"
      MEMORY: "512M"
      DIFFICULTY: "normal"
      GAMEMODE: "survival"
      MOTD: "Welcome to Abdullah's server!"
      ONLINE_MODE: "FALSE"
      DEFAULT_OP: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
    volumes:
      - minecraft_data:/data
      - ./plugins:/data/plugins:rw
    user: "1000:1000"
    restart: unless-stopped

volumes:
  minecraft_data:
