services:
  - type: web
    name: minecraft-server
    runtime: docker
    plan: standard
    region: oregon
    healthCheckPath: null
    healthCheckDisabled: true
    autoDeploy: true
    envVars:
      - key: EULA
        value: "TRUE"
      - key: TYPE
        value: vanilla
      - key: VERSION
        value: latest
      - key: MEMORY
        value: "450M"
      - key: DIFFICULTY
        value: normal
      - key: GAMEMODE
        value: survival
      - key: MOTD
        value: "Welcome to Abdullah's server!"
      - key: ONLINE_MODE
        value: "FALSE"
    ports:
      - port: 25565
        protocol: TCP
