name: Avengers
version: 1.0
main: com.aura.avengers.AvengersPlugin
description: Avengers themed items and abilities
commands:
  mjolnir:
    description: Get Mjolnir
    usage: /mjolnir
  ironman:
    description: Get Iron Man armor
    usage: /ironman
  captainshield:
    description: Get Captain America shield
    usage: /captainshield
  hawkeyearrows:
    description: Get Hawkeye arrows
    usage: /hawkeyearrows
