#Minecraft server properties
#Mon Feb 02 18:05:27 MST 2026
accepts-transfers=true
allow-flight=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-jmx-monitoring=true
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=true
management-server-host=0.0.0.0
management-server-port=9900
management-server-secret=VjQsPUhYMMj5MamyE1teVDIItz76AH8IZmK5RCOM
management-server-tls-enabled=false
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=600000
max-world-size=29999984
motd=§7Welcome to §9King SMP§7\!
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=30
prevent-proxy-connections=false
previews-chat=false
query.port=9898
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://packs.download/DNwoGxIZXi5JbO0G/hjFxkkwkBtmQiTt1.zip
resource-pack-id=686a4678-6b6b-776b-4274-6d5169547431
resource-pack-prompt=""
resource-pack-sha1=ef4d434668b859229732ba37489e5ff785bf2048
server-ip=
server-port=51309
simulation-distance=5
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=5
white-list=false
